import React, { useEffect } from 'react';
import Head from 'next/head'
import { useRouter } from 'next/router';
import styles from '@/styles/Product.module.css'
import Image from 'next/image';
import data from '../../data/data.json';

const ProductPage = () => {
    const router = useRouter();
    const { id } = router.query;

    const productButton = (coords:[number, number]) => {
        const url = new URL(window.location.href);
        url.pathname = `/map`;

        url.searchParams.set('lat', coords[0].toString());
        url.searchParams.set('long', coords[1].toString());
        window.location.href = url.toString();
    }

    return (
        <>
            <Head>
                <title>Ci</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="@public/next.svg" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>{id}</h1>
                <div>
                    {data.map((item, index) => ( // map through the data
                        <div key={index} className={styles.card} onClick={() => {productButton([item.gps[0],item.gps[1]])}}>
                            <Image src={item.logo} alt={item.name} width={100} height={100} />
                            <div>                                
                                <h2>{item.name}</h2>
                                <p>{item.reviews.length} Reviews</p>
                                <p>{item.address}</p>
                            </div>
                        </div>
                    ))}
                </div>
            </main>
        </>
    );
};

export default ProductPage;