"use client"

import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react';
import axios from 'axios';
import Image from 'next/image';
import { get } from 'http';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [data, setData] = useState([]);
  const [imgs, setImgs] = useState<string[]>([]);
  const [loading, setLoading] = useState(false);
  const [timeElapsed, setTimeElapsed] = useState(0);
  

  const getProducts = async () => {
    setImgs([]);
    setLoading(true);
    const startTime = Date.now();

    const urlParams = new URLSearchParams(window.location.search);
    let region = urlParams.get('city');

    if(region == null || region == ""){
      await axios.get('http://ip-api.com/json/')
        .then(response => {
          region = response.data.region;
        })
        .catch(error => console.error('Error fetching IP information:', error));
      }
      console.log(region);

    const response = await fetch(`/api/getProducts?input=${region}`);
    let data = await response.json();

    setLoading(false);
    setData(data.data);

    const endTime = Date.now();
    setTimeElapsed((endTime - startTime)/1000);

    await getImages();
  }

  const getImages = async () => {
    setImgs([]);
    for (const product of data) {
      let response;
      if(loading){
        setImgs([])
        return;
      }
      try {
        response = await fetch(`/api/getImgs?input=${product[1]}`);
      } catch {
        setImgs((prevImgs: string[]) => [...prevImgs, "/next.svg"]);
        return;
      }
      let data = await response?.json();
      if (data && data.data) {
        const img = data.data.find((element: string) => element.includes('GeographicalSigns')) || null;
        setImgs((prevImgs: string[]) => [...prevImgs, img != null ? img : "/next.svg"]);
      }
    }
  };

  const searchButton = () => {
    const newUrl = new URL(window.location.href);
    newUrl.searchParams.set('city', '09');

    window.location.href = newUrl.toString();
  }
  
  useEffect(() => {
    getImages();
  }, [data]);

  useEffect(() => {
    getProducts();  
  },[]);

  return (
    <>
      <Head>
        <title>Ci</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../../public/next.svg" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Ci</h1>
        <button className={styles.card} style={{backgroundColor:"#fff1", padding:10, margin:10, borderRadius:10}} onClick={searchButton}>Get Products</button>
        {(data.length !== 0 || loading) && (loading ?
        <div>
          <p className={styles.code} style={{textAlign:"center"}}>Loading...</p>
          <div className={styles.spinner}></div>
        </div>: 
        <div style={{backgroundColor:"#fff1", padding:10, margin:10, borderRadius:10}}>
          <p className={styles.code} style={{textAlign:"center", marginTop:10}}>Time Elapsed: {timeElapsed} seconds</p>
          <br></br>
          {data.map((product, index) => {
            return (
              <div key={index} className={styles.card}>
                <Image src={imgs[index]?imgs[index]:"/next.svg"} alt="Product Image" width={200} height={200} id={`ci${index}`}/>
                <p className={styles.code}>{product[0]}</p>
              </div>
            )
          })}
        </div>
        )}
      </main>
    </>
  )
}
